blank_issues_enabled: true
contact_links:
  - name: Community (Headless WordPress Discord)
    url: https://faustjs.org/discord
    about: Join our community Discord server for real-time discussions and community support

  - name: Support / Feature Request / General Help
    url: https://github.com/wpengine/hwptoolkit/discussions
    about: Please use our GitHub Discussions for questions, feature ideas, and general help
